### PR TITLE
Add continuous integration

### PR DESCRIPTION
**Pull request by gllmflndn**
Use GitHub Actions and Octave, in preparation of further pull requests.

### CODE REVIEW

**Review by georgeoneill — APPROVED** [review]

**Comment by georgeoneill** [comment]
Hi Guillaume,

I have to admit this is the first time I have used pulls in this way. Would you like me to marge this back into the master?

**Comment by gllmflndn** [comment]
Let me know if you want me to operate differently - but, yes, otherwise please merge if you are happy with the changes.

**Comment by georgeoneill** [comment]
This works for me, let me know when you are done with a branch and I'll merge. :)

**Comment by gllmflndn** [comment]
Thanks - for a cleaner history (and hide my mistakes) you might want to squash/rebase merge the other PRs.

**Pull request merged**
